/*
    Conditional configuration file for compiling OpenAL sources. This is
    generated by CMake for each different platform, and changes are done
    by hand to work for each and every ABI that AndroidOpenAL targets.

    ONLY TOUCH ANYTHING IF YOU REALLY KNOW WHAT THIS IS, AND EXPECT IT TO BREAK.
*/

#ifdef ARMEABI

#define AL_API  __attribute__((visibility("protected")))
#define ALC_API __attribute__((visibility("protected")))
#define ALSOFT_VERSION "1.17.2"
#define ALIGN(x) __attribute__((aligned(x)))
#define HAVE_OPENSL
#define HAVE_WAVE
#define HAVE_STAT
#define HAVE_LRINTF
#define HAVE_MODFF
#define HAVE_STRTOF
#define HAVE_STRNLEN
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG 8
#define HAVE_C99_VLA
#define HAVE_C99_BOOL
#define HAVE_C11_STATIC_ASSERT
#define HAVE_C11_ALIGNAS
#define HAVE_GCC_DESTRUCTOR
#define HAVE_GCC_FORMAT
#define HAVE_STDINT_H
#define HAVE_STDBOOL_H
#define HAVE_STDALIGN_H
#define HAVE_DLFCN_H
#define HAVE_MALLOC_H
#define HAVE_DIRENT_H
#define HAVE_STRINGS_H
#define HAVE_SYS_SYSCONF_H
#define HAVE_FLOAT_H
#define HAVE_FENV_H
#define HAVE_PTHREAD_SETSCHEDPARAM
#define HAVE_PTHREAD_SETNAME_NP

#endif
#ifdef ARMEABI_V7A

#define AL_API  __attribute__((visibility("protected")))
#define ALC_API __attribute__((visibility("protected")))
#define ALSOFT_VERSION "1.17.2"
#define ALIGN(x) __attribute__((aligned(x)))
#define HAVE_OPENSL
#define HAVE_WAVE
#define HAVE_STAT
#define HAVE_LRINTF
#define HAVE_MODFF
#define HAVE_STRTOF
#define HAVE_STRNLEN
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG 8
#define HAVE_C99_VLA
#define HAVE_C99_BOOL
#define HAVE_C11_STATIC_ASSERT
#define HAVE_C11_ALIGNAS
#define HAVE_GCC_DESTRUCTOR
#define HAVE_GCC_FORMAT
#define HAVE_STDINT_H
#define HAVE_STDBOOL_H
#define HAVE_STDALIGN_H
#define HAVE_DLFCN_H
#define HAVE_MALLOC_H
#define HAVE_DIRENT_H
#define HAVE_STRINGS_H
#define HAVE_SYS_SYSCONF_H
#define HAVE_FLOAT_H
#define HAVE_FENV_H
#define HAVE_PTHREAD_SETSCHEDPARAM
#define HAVE_PTHREAD_SETNAME_NP

#endif
#ifdef ARM64_V8A

#define AL_API  __attribute__((visibility("protected")))
#define ALC_API __attribute__((visibility("protected")))
#define ALSOFT_VERSION "1.17.2"
#define ALIGN(x) __attribute__((aligned(x)))
#define HAVE_POSIX_MEMALIGN
#define HAVE_NEON
#define HAVE_OPENSL
#define HAVE_WAVE
#define HAVE_STAT
#define HAVE_LRINTF
#define HAVE_MODFF
#define HAVE_STRTOF
#define HAVE_STRNLEN
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define HAVE_C99_VLA
#define HAVE_C99_BOOL
#define HAVE_C11_STATIC_ASSERT
#define HAVE_C11_ALIGNAS
#define HAVE_GCC_DESTRUCTOR
#define HAVE_GCC_FORMAT
#define HAVE_STDINT_H
#define HAVE_STDBOOL_H
#define HAVE_STDALIGN_H
#define HAVE_DLFCN_H
#define HAVE_MALLOC_H
#define HAVE_DIRENT_H
#define HAVE_STRINGS_H
#define HAVE_SYS_SYSCONF_H
#define HAVE_FLOAT_H
#define HAVE_FENV_H
#define HAVE_PTHREAD_SETSCHEDPARAM
#define HAVE_PTHREAD_SETNAME_NP
#define HAVE_PTHREAD_MUTEX_TIMEDLOCK

#endif
#ifdef MIPS

#define AL_API  __attribute__((visibility("protected")))
#define ALC_API __attribute__((visibility("protected")))
#define ALSOFT_VERSION "1.17.2"
#define ALIGN(x) __attribute__((aligned(x)))
#define HAVE_OPENSL
#define HAVE_WAVE
#define HAVE_STAT
#define HAVE_LRINTF
#define HAVE_MODFF
#define HAVE_STRTOF
#define HAVE_STRNLEN
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG 8
#define HAVE_C99_VLA
#define HAVE_C99_BOOL
#define HAVE_C11_STATIC_ASSERT
#define HAVE_C11_ALIGNAS
#define HAVE_GCC_DESTRUCTOR
#define HAVE_GCC_FORMAT
#define HAVE_STDINT_H
#define HAVE_STDBOOL_H
#define HAVE_STDALIGN_H
#define HAVE_DLFCN_H
#define HAVE_MALLOC_H
#define HAVE_DIRENT_H
#define HAVE_STRINGS_H
#define HAVE_SYS_SYSCONF_H
#define HAVE_FLOAT_H
#define HAVE_FENV_H
#define HAVE_PTHREAD_SETSCHEDPARAM
#define HAVE_PTHREAD_SETNAME_NP

#endif
#ifdef MIPS64

#define AL_API  __attribute__((visibility("protected")))
#define ALC_API __attribute__((visibility("protected")))
#define ALSOFT_VERSION "1.17.2"
#define ALIGN(x) __attribute__((aligned(x)))
#define HAVE_POSIX_MEMALIGN
#define HAVE_OPENSL
#define HAVE_WAVE
#define HAVE_STAT
#define HAVE_LRINTF
#define HAVE_MODFF
#define HAVE_STRTOF
#define HAVE_STRNLEN
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define HAVE_C99_VLA
#define HAVE_C99_BOOL
#define HAVE_C11_STATIC_ASSERT
#define HAVE_C11_ALIGNAS
#define HAVE_GCC_DESTRUCTOR
#define HAVE_GCC_FORMAT
#define HAVE_STDINT_H
#define HAVE_STDBOOL_H
#define HAVE_STDALIGN_H
#define HAVE_DLFCN_H
#define HAVE_MALLOC_H
#define HAVE_DIRENT_H
#define HAVE_STRINGS_H
#define HAVE_SYS_SYSCONF_H
#define HAVE_FLOAT_H
#define HAVE_FENV_H
#define HAVE_PTHREAD_SETSCHEDPARAM
#define HAVE_PTHREAD_SETNAME_NP
#define HAVE_PTHREAD_MUTEX_TIMEDLOCK

#endif
#ifdef X86

#define AL_API  __attribute__((visibility("protected")))
#define ALC_API __attribute__((visibility("protected")))
#define ALSOFT_VERSION "1.17.2"
#define ALIGN(x) __attribute__((aligned(x)))
#define HAVE_SSE
#define HAVE_SSE2
#define HAVE_SSE3
#define HAVE_NEON
#define HAVE_OPENSL
#define HAVE_WAVE
#define HAVE_STAT
#define HAVE_LRINTF
#define HAVE_MODFF
#define HAVE_STRTOF
#define HAVE_STRNLEN
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG 8
#define HAVE_C99_VLA
#define HAVE_C99_BOOL
#define HAVE_C11_STATIC_ASSERT
#define HAVE_C11_ALIGNAS
#define HAVE_GCC_DESTRUCTOR
#define HAVE_GCC_FORMAT
#define HAVE_STDINT_H
#define HAVE_STDBOOL_H
#define HAVE_STDALIGN_H
#define HAVE_DLFCN_H
#define HAVE_MALLOC_H
#define HAVE_DIRENT_H
#define HAVE_STRINGS_H
#define HAVE_CPUID_H
#define HAVE_SYS_SYSCONF_H
#define HAVE_FLOAT_H
#define HAVE_FENV_H
#define HAVE_GCC_GET_CPUID
#define HAVE_PTHREAD_SETSCHEDPARAM
#define HAVE_PTHREAD_SETNAME_NP

#endif
#ifdef X86_64

#define AL_API  __attribute__((visibility("protected")))
#define ALC_API __attribute__((visibility("protected")))
#define ALSOFT_VERSION "1.17.2"
#define ALIGN(x) __attribute__((aligned(x)))
#define HAVE_POSIX_MEMALIGN
#define HAVE_SSE
#define HAVE_SSE2
#define HAVE_SSE3
#define HAVE_SSE4_1
#define HAVE_NEON
#define HAVE_OPENSL
#define HAVE_WAVE
#define HAVE_STAT
#define HAVE_LRINTF
#define HAVE_MODFF
#define HAVE_STRTOF
#define HAVE_STRNLEN
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define HAVE_C99_VLA
#define HAVE_C99_BOOL
#define HAVE_C11_STATIC_ASSERT
#define HAVE_C11_ALIGNAS
#define HAVE_GCC_DESTRUCTOR
#define HAVE_GCC_FORMAT
#define HAVE_STDINT_H
#define HAVE_STDBOOL_H
#define HAVE_STDALIGN_H
#define HAVE_DLFCN_H
#define HAVE_MALLOC_H
#define HAVE_DIRENT_H
#define HAVE_STRINGS_H
#define HAVE_CPUID_H
#define HAVE_SYS_SYSCONF_H
#define HAVE_FLOAT_H
#define HAVE_FENV_H
#define HAVE_GCC_GET_CPUID
#define HAVE_PTHREAD_SETSCHEDPARAM
#define HAVE_PTHREAD_SETNAME_NP
#define HAVE_PTHREAD_MUTEX_TIMEDLOCK

#endif
